runtime: nodejs18
instance_class: F1
env_variables:
  NODE_ENV: 'production'

handlers:
- url: /Public
  static_dir: Public

- url: /Public
  static_dir: Public/UserFiles


- url: /.* 
  script: auto
  